### PR TITLE
Improved displaying of translation changes

### LINKED ISSUE #1570: Better display of changes
After request #1569:

Still in the history page, new translation strings are quite hard to check/read (changed introduced maybe 6 months ago): merge of colors (red for removed characters ...) and font style (strikes for removed characters ...).

I suggest to add an option to switch between 2 display styles for the new translations, depending on user preferences.

Proposed named for this option: "Display mode for the translated strings" (in history page and / or email notifications).
Values could be "Highlight changes" or "Raw display (no change highlighted)".
Maybe the same should apply in the mail notifications.

This option can be set globally in the user profil.

Thanks,

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/47410434-better-display-of-changes?utm_campaign=plugin&utm_content=tracker%2F253393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F253393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by nijel**
Now uses diff-match-patch with semantic cleanup. This seems to produce
nicely readable output in most cases.

Fixes #1570

Signed-off-by: Michal Čihař <michal@cihar.com>

Before submitting pull request, please ensure that:

- [x] Every commit has message which describes it
- [x] Every commit is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any code changes come with testcase
- [x] Any new functionality is covered by user documentation

### CODE REVIEW

**Comment by nijel** [comment]
If you want to see what the diff will look like with this change, you can use https://neil.fraser.name/software/diff_match_patch/demos/diff.html

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by fitojb** [comment]
This seems to have regressed since the monospaced font was introduced in the lists of changes.

**Comment by nijel** [comment]
@fitojb Thanks for pointing out, it's a bug in changes display and I've fixed that now in f9fa63ae136bcfd0ff5225e608fcd45bf9109224 and f9602da327540ef66cc96da04559580aa69aee7f.

**Pull request merged**
