### PR TITLE
Fix latest changes UI overlapping in Insights

### PR DESCRIPTION
**Pull request by meel-hd**
## Proposed changes
Fixed the Mobile UI overlapping in Latest Changes 
image

Closes: #12247 

## Checklist

- [x] Lint and unit tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added documentation to describe my feature.
- [x] I have squashed my commits into logic units.
- [x] I have described the changes in the commit messages.

### CODE REVIEW

**Comment by meel-hd** [comment]
While **Latest Additions** in Insights is fixed now on mobile. The **History** tab in Insights have the same issue of UI overlapping on mobile.
image
I am working on it.

**Comment by nijel** [comment]
I'm starting to consider whether this is actually the correct direction. It really looks like a pop-up overlapping the user avatar and not really bound to the record. I will try to come up with something different here looking more like a toolbar (something like GitHub has when writing a comment).

**Comment by meel-hd** [comment]
Why not hide those actions. Until the 3 dots icon (should be on the top right corner) is clicked.

**Comment by meel-hd** [comment]
[c31f610](https://github.com/WeblateOrg/weblate/pull/12252/commits/c31f61067e53e9be49b5ce7c01b20c7a58e278e1) proposes this layout on mobile ⬇️
image

**Comment by meel-hd** [comment]
**Comments and History Preview**

https://github.com/user-attachments/assets/20dce3b0-3894-4587-b03e-f7e60a10623d

**Pull request merged**
