### PR TITLE
Make the UI modern and Minimal

### PR DESCRIPTION
**Pull request by meel-hd**
### Summary:
Improved UI to be more minimal by reducing the number of colors used and their intensity. Also made it Modern by using more rounded corners and subtle shadows. Plus started depending more on css variables than hard coded values.

### Modifications include changes in:
- Navbar and its items
- Dropdown menus
- Input fields
- Nav Pills
- Panels and their headings

These changes while being opinionated they introduce a beautiful and modern UI. More suitable and aligned to the current trends and the community.

Relalted: #7655

## Checklist

- [x] Lint and unit tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added documentation to describe my feature.
- [x] I have squashed my commits into logic units.
- [x] I have described the changes in the commit messages.

#### Main Page (note navbar, dropdown menu, and nav pills)
b
#### Statistics Page (note panels and their headings)
a

## Summary by CodeRabbit

- **New Features**
	- Introduced new CSS classes for improved navigation and UI components, including `.navbar-default`, `.panel`, and `.multi-wrapper`.
	- Enhanced styling for buttons, input fields, and progress bars with consistent border radius and color variables.

- **Improvements**
	- Updated CSS variables for better maintainability and responsiveness, including support for dark mode.
	- Refined hover states and active visuals for navigation elements.

- **Bug Fixes**
	- Adjusted the navigation bar's styling for a more cohesive design by removing the `navbar-inverse` class.

### CODE REVIEW

**Comment by nijel** [comment]
Thanks, but I don't think this is something we should do now. We will definitely work on UI in the future, but this needs to start with UI design and implementing desired changes then. Making random UI changes without prior decision is not the way to go.

Moreover, when making UI changes, there are some existing features to be considered:

* There is [appearance customization](https://docs.weblate.org/en/latest/admin/admin.html#manage-appearance) in the management interface and that one should not be broken (removing the background from navbar does that because its color is one of the things users can customize).
* The dark theme is also user selectable, thus using media query is not the way to introduce dark theme changes, they need to go into `weblate/static/style-dark.css`. Ideally, this file would only change variables which are used in the main theme, but we're not there.

And some changes look worse to me. The navbar menu is simple and aligned:

obrazek

But with button like selection and navbar shadow it looks more messy:

obrazek

**Comment by meel-hd** [comment]
Oh! That's unfortunate. while effort was made on these changes I believe it could have been used somewhere else more beneficial and aligned with the project if the changes were discussed before. While the issues with the menu and dark-theme rules could be easily fixed, I think that's irrelevant to discuss anymore.

It was a fun  little experiment I thought it would produce beautiful results but beauty is subjective. I wonder what are some of the good things you see appropriate; maybe we can incorporate or modify a little bit so they are.

**Comment by nijel** [comment]
Generally I'm not opposed to UI improvements, but if it is completely changes what users see, it needs to be carefully considered before.

I want you to focus on working on issues for now so that you can learn the code structure (which definitely would use some improvements like using CSS variables which were not widely supported back then when these CSS were initially written) and Weblate features (which also influence what you can do in the CSS to avoid breaking them). We will be definitely doing more UI changes in the future, but for the bigger changes I prefer to start with an UX design and then implementing them rather than doing that without having a consistent design guide.

**Comment by meel-hd** [comment]
Okay. I understand

**Pull request closed without merging**
