### PR TITLE
Add support for specifying legal documents outside Weblate

### PR DESCRIPTION
**Pull request by nijel**
This is lightweight variant to using legal app.

Fixes https://github.com/WeblateOrg/docker/issues/76

Signed-off-by: Michal Čihař <michal@cihar.com>

Before submitting pull request, please ensure that:

- [x] Every commit has message which describes it
- [x] Every commit is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any code changes come with testcase
- [x] Any new functionality is covered by user documentation

### CODE REVIEW

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by dg-otrs** [comment]
Hey, 

how should this work? Setting an https link?

LEGAL_URL = 'https://xxx.com/legal-notice/'

I dont get it...

Cheers

Dennis

**Comment by nijel** [comment]
Apparently the related code was accidentally removed from the template, so it doesn't work at the moment.

**Comment by nijel** [comment]
...fixed in 484c7544c3bf2e59c812394f365cfd80af8fd2f9

**Pull request merged**
