### PR TITLE
Add skip unsaved changes confirmation

### PR DESCRIPTION
**Pull request by meel-hd**
## Proposed changes
- Fixed buttons visual heirarchy in  translation editor.
- Added a confirmation popup when the user clicks skip if there are unsaved changes.

close: #13050

## Checklist

- [x] Lint and unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added documentation to describe my feature.
- [ ] I have squashed my commits into logic units.
- [x] I have described the changes in the commit messages.

## Other information
image

### CODE REVIEW

**Comment by gcb** [comment]
Thanks. that was fast!

code for confirmation :+1: 

I'm not familiar with [bootstrap naming convention for button roles](https://getbootstrap.com/docs/4.0/components/buttons/)... they seem to be exclusive for color not meaning... but i assume the the default form action "save and continue" might be `btn-default`. (and then you could even leave the other buttons as btn-primary instead of btn-link, i guess)

**Comment by nijel** [comment]
Let's split this PR into two:

* JavaScript confirmation, that one is clear and can be merged right now.
* UI changes. I think these really should stay as buttons, using links for saving/suggesting seems wrong. The skip button could be a link, but it might be better to have all of them as buttons for UI consistency. What might be a better approach is to switch `btn-primary` and `btn-warning` colors in the dark theme. Currently, they are the same as in light and that brings attention to different buttons as the background is inverse.

PS: The button classes really don't have a real meaning, for historical reasons, Weblate is using `btn-warning` as secondary level of buttons.

**Comment by meel-hd** [comment]
@nijel okay, I'll make this PR concerned with the confirmation logic only.

**Comment by nijel** [comment]
@meel-hd I think this is a good approach, please create a separate PR for that.

**Pull request merged**
