### PR TITLE
Spelling: Project contributions

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by nijel** [comment]
This was changed in 91dfa4aa218193061535713d3a570ce1ae6036b5 based on feedback from translators, for example @ldmpub 

Can we please get some consensus on this before changing it again?

**Comment by ldmpub** [comment]
Hi, (and happy new year to you all!)

I have no more context in mind for this (these?) change.
Is it contributions for "1" project or for "all" projects ?
A screen capture where this string is displayed can be usefull...

Thanks,

**Comment by comradekingu** [comment]
@ldmpub 
It is the English variant of https://hosted.weblate.org/user/kingu/
image

**Review by orangesunny — APPROVED** [review]
"Project contributions" was there historically and users were asking, let’s go with "Projects with contribution" that should be clear to everyone.

**Comment by comradekingu** [comment]
@orangesunny "Projects with contributions" more-so means something along the lines of "Projects that have contributed".
I tried to find the rule, but it is the same as "star fields" "dog owner" "flight assistant" "burger flipper" and so on.

**Comment by ldmpub** [comment]
Ok, this 'tab" label is displayed in the user profile and means "All projects the current user has contributed to"...

What about "Contributed projects"? (I apologies if this is bad english 😐.

**Comment by comradekingu** [comment]
@ldmpub I think "Contributed projects" more closely resembles "projects that the user has contributed to the platform",
like "contributed money" would be donations.
Or, it describes the project as having been contributed, as opposed to one having been made or created by itself in-house.

I found "User contribution pages _are_" in https://en.wikipedia.org/wiki/Help:User_contributions and there are plenty of "project contributions. It would in that case be "Pages for user contributions".
There are no hits for "projects contributions", but plenty for "project contributions". I will find the actual rule sooner or later ;)

**Pull request merged**
