### PR TITLE
incosistent permissions in template fixed

### PR DESCRIPTION
**Pull request by GeorgeBekh**
Made rules of rendering the body same as rendering the button 
https://github.com/WeblateOrg/weblate/blob/master/weblate/templates/translation.html#L63-L65

- [x] Every commit has message which describes it
- [x] Every commit is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any code changes come with testcase
- [ ] Any new functionality is covered by user documentation

### CODE REVIEW

**Comment by GeorgeBekh** [comment]
May be let's make separate variable for each tab to avoid such inconsistency in future?

**Comment by nijel** [comment]
This is actually the wrong way, both things should be checked. IMHO it's better to do all the checks here:

https://github.com/WeblateOrg/weblate/blob/2e7bb66df33ef1798e1cd749e3a036ddca1f992c/weblate/auth/permissions.py#L167-L172

**Comment by GeorgeBekh** [comment]
Can you give an example?

**Comment by nijel** [comment]
I've implemented it in 45043043a31289101444185820a99c8735cb56e0.

**Pull request closed without merging**
