### PR TITLE
refactor: Utilize expression index for auth

### LINKED ISSUE #9973: Utilize expression index for auth
### Describe the problem

Weblate does manually create index using `CREATE UNIQUE INDEX` during the `weblate.auth` model migration.

### Describe the solution you'd like

This should be changed to use Django standard expression index `UniqueConstraint(...Upper(...))` instead for better readability and portability.

### Describe alternatives you've considered

_No response_

### Screenshots

_No response_

### Additional context

Need Django 4.0+ (Weblate already requires 4.2).

See also https://stackoverflow.com/a/69752763/225718 and https://stackoverflow.com/a/66966391/225718

### PR DESCRIPTION
**Pull request by mohebmithani**
- resolves #9973 
- Have used Django standard expression index UniqueConstraint(...Upper(...)) for username and email fields of User table. I've removed manual index creation from migration.

## Checklist

- [x] Lint and unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added documentation to describe my feature.
- [x] I have squashed my commits into logic units.
- [x] I have described the changes in the commit messages.

### CODE REVIEW

**Review by nijel — COMMENTED** [review]
I don't think the migrations will work this way. Existing installations have index created manually and you add another migration to create it. If both indexes are really the same, you should replace the `RunPython` step with `AddConstraint` one. If Django generated inxex expression is different, just mark the `RunPython` step as elidable (so that it can be removed next time the migrations are squashed) and add a migration to execute `DROP INDEX` manually before re-creating them.

**Comment by mohebmithani** [comment]
> I don't think the migrations will work this way. Existing installations have index created manually and you add another migration to create it. If both indexes are really the same, you should replace the `RunPython` step with `AddConstraint` one. If Django generated inxex expression is different, just mark the `RunPython` step as elidable (so that it can be removed next time the migrations are squashed) and add a migration to execute `DROP INDEX` manually before re-creating them.

Okay i'll look into it and fix it. Thanks for the review

**Comment by nijel** [comment]
You can see the migration failure for existing installs at https://github.com/WeblateOrg/weblate/actions/runs/6372487199/job/17304733816?pr=10077

**Comment by mohebmithani** [comment]
> I don't think the migrations will work this way. Existing installations have index created manually and you add another migration to create it. If both indexes are really the same, you should replace the `RunPython` step with `AddConstraint` one. If Django generated inxex expression is different, just mark the `RunPython` step as elidable (so that it can be removed next time the migrations are squashed) and add a migration to execute `DROP INDEX` manually before re-creating them.

@nijel I've implemented your first suggestion.

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by mohebmithani** [comment]
> Merged, thanks for your contribution!

Thanks.

**Pull request merged**
