### PR TITLE
Improve audit log messages for authenticating

### PR DESCRIPTION
**Pull request by nijel**
The current form of method:name can be confusing (eg. Password:user), so
better describe it with words.

Signed-off-by: Michal Čihař <michal@cihar.com>

Before submitting pull request, please ensure that:

- [x] Every commit has message which describes it
- [x] Every commit is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any code changes come with testcase
- [x] Any new functionality is covered by user documentation

### CODE REVIEW

**Comment by nijel** [comment]
@comradekingu I'd really like to hear your opinion here on changing audit log strings.

**Comment by comradekingu** [comment]
@nijel "Could not log in as {name} with {method}"?  What are the methods?

And
"Somebody has attempted to register using your email address"
or (if I understand it correctly)
"Confirm registration on Weblate for this e-mail address."

**Comment by nijel** [comment]
The `{method}` is name of authentication method. It's either "Password" or name of third party service (eg. "GitHub", "Google", "Facebook", ...). The `{name}` is identifier from this service, it doesn't have to be username or email, it can be as well numerical ID (eg. for GitHub or Facebook) or URL (for OpenID based providers such as Fedora).

**Comment by comradekingu** [comment]
Should be "password" to fit it into a sentence.
Changed to "with {name}, but one case doesn't really cover all here.
I imagine it is an active error in some language.
Maybe do one case for each service?

"You can now log in with {name} using {method}"?
"You can no longer log in with {name} using {method}"
"Logged on with {name} using {method} from a new device"
"Could not log in with {name} using {method}"
"Somebody has attempted to register using your email address"
/
"Confirm registration on Weblate for this e-mail address."
"Account locked due to many failed logins."

**Comment by nijel** [comment]
It doesn't matter whether it's password or Password, it won't fit nicely when localizing anyway (that's why I used the '({{method}}:{{user}})` form in the beginning because it doesn't need declining).

Maybe it's better to special case the password authentication completely and avoid to compose the sentence in this case. For third party services it will stay though...

**Comment by nijel** [comment]
@comradekingu I've changed it based on your suggestions, but looking at it again it probably doesn't work well. The problem is that `user` is more an internal identifier of the third party service than something user would be aware of and this way it gives it too much of attention:

* You can now log in with http://nijel.id.fedoraproject.org/ using Fedora
* You can now log in with 148674 using GitLab
* You can now log in with 10205554029310662 using Facebook

I've changed it to give more attention to the service name:

* You can now log in using Fedora (http://nijel.id.fedoraproject.org/
* You can now log in using GitLab (148674)
* You can now log in using Facebook (10205554029310662)

Also I've separated messages for password authentication to avoid confusion in that case.

Again, feedback is welcome ;-).

**Pull request merged**
