### PR TITLE
Fix Docker docs //EMAIL_HOST_* vars to EMAIL_*

### PR DESCRIPTION
**Pull request by XaviTorello**
It seems that there are some typos with `EMAIL_HOST_USER` and `EMAIL_HOST_PASSWORD` vars.

Reviewing the code it seems that should be `EMAIL_USER` and `EMAIL_PASSWORD`.

### CODE REVIEW

**Comment by nijel** [comment]
Why do you think there is a typo? The both variables are correct, see https://docs.djangoproject.com/en/2.2/ref/settings/#email-host-user and https://docs.djangoproject.com/en/2.2/ref/settings/#email-host-password

**Comment by nijel** [comment]
See also https://github.com/WeblateOrg/weblate/pull/1539

**Comment by XaviTorello** [comment]
Sorry @nijel, I don't want to disturb you...

I'm trying to create a `helm` `Chart` for `weblate` (based from the docker-compose repo) and both env vars seems to be abled: 

https://github.com/WeblateOrg/docker-compose/blob/master/environment#L53-L56
 https://github.com/WeblateOrg/weblate/blob/ac8e2c62554150c11a83fba315e8325db0f153bf/weblate/settings_docker.py#L967

Maybe it's a little bit confusing and can be improved using just the normal `Django` vars. 

Provably it's something that should be fixed in the composition.

**Comment by nijel** [comment]
The variables were misnamed, we've fixed them to follow Django ones, but for compatibility with existing setups the wrong names are also accepted, see https://github.com/WeblateOrg/weblate/pull/1539

There is helm chart being created in https://github.com/WeblateOrg/docker-compose/pull/8, maybe you can join the discussion there.

**Pull request closed without merging**
