### PR TITLE
docs: docker: missing _HOST in variables

### PR DESCRIPTION
**Pull request by dachary**

### CODE REVIEW

**Comment by nijel** [comment]
Well even though the variable doesn't match Django, this is how it's implemented: https://github.com/WeblateOrg/docker/blob/docker/settings.py#L726

**Comment by dachary** [comment]
@nijel I realize that now, my bad for assuming systematic naming convention and thanks for your comment.

**Comment by nijel** [comment]
Well not using systematic naming was a mistake. Now the question is whether to fix that (and break some existing setups) or keep it (and stay inconsistent)...

**Comment by nijel** [comment]
I'd probably fix the naming with compatibility for the old ones for some time...

**Comment by nijel** [comment]
Well, even Django is pretty inconsistent here - there is EMAIL_PORT, but EMAIL_HOST_USER ;-).

**Comment by nijel** [comment]
Merged, I've changed the Docker settings to accept both options.

**Pull request merged**
