### PR TITLE
basic languages: factor in the default variant of languages without a base form

### PR DESCRIPTION
**Pull request by ray2c**
A regression was introduced a while back when a couple of languages were split into their respective couple of variants in [language-data](https://github.com/WeblateOrg/language-data/commits/main/weblate_language_data/languages.py?since=2023-04-18&until=2023-04-18) and, thereby, here got filtered out of the default list of basic languages altogether since they no longer present themselves in their base form.

## Proposed changes

Instead of adding them to `UNDERSCORE_EXCEPTIONS` to resurrect their pre-split position, this PR tries to adopt a more future-proof approach to the default list of basic languages to include the default variant of languages without a base form (when an alias for which is present) such that they would not be filtered out of the default list of basic languages altogether just because, some point in time, they cease to stand alone 'bare feet' in Weblate's list of languages.

## Checklist

- [ ] Lint and unit tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added documentation to describe my feature.
- [ ] I have squashed my commits into logic units.
- [x] I have described the changes in the commit messages.

## Other information

Subject to manual overrides, the list of basic languages is presented to the user in the "Start new translation" page, which says they would need to contact the project maintainer if they wish to add a language not on that list.

### CODE REVIEW

**Comment by nijel** [comment]
Can you please also add tests for this behavior?

**Comment by ray2c** [comment]
Hi, thanks for the prompt response!  (and the great software of course)
I'm sorry that this's actually my first PR (and first time coding Python), so please kindly bear with me : )
May I ask the silly question if there's any quick pointer for the tests which I might look at?
Cheers,
with best regards

**Comment by ray2c** [comment]
Thanks for the prompt response!  Kindly bear with me as this is my first time coding in Python and submitting a PR : )
I've poked around a bit the tests; it seems there isn't a direct test on `BASIC_LANGUAGES` (forgive me if I'm wrong) but I've included an indirect test: I gather the 'add new language' form presented to the user (other than the owner, I think) by default is restricted to `BASIC_LANGUAGES` (if I'm not mistaken), adding the default variant of a language without a base form should succeed if it is included as one of the `BASIC_LANGUAGES`.
Kindly let me know if you've any insights or pointers on any improvement.  Thank you!

**Comment by nijel** [comment]
Indeed, there is no direct test for this. Maybe it would be better to have one because this way it is not apparent what you are testing.

**Comment by ray2c** [comment]
Sounds like a good idea.  A separate test case for the default list of basic languages has been added which hopefully might be more comprehensive and spell out the logic with some examples.

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by ray2c** [comment]
Thank you very much for your comments and review!

**Pull request merged**
