### PR TITLE
Xliff fixes

### PR DESCRIPTION
**Pull request by nijel**
See discussion on https://github.com/WeblateOrg/weblate/issues/2668

This code really deserves some tests.

### CODE REVIEW

**Comment by SomeBdyElse** [comment]
The reading of the source string works fine now. Unfortunately, the saved strings still get truncated to their first character. 

Change of the monolingual source file in git
```diff
--- a/app/web/typo3conf/ext/usersaccassite/Resources/Private/Language/locallang.xlf
+++ b/app/web/typo3conf/ext/usersaccassite/Resources/Private/Language/locallang.xlf
@@ -4,11 +4,9 @@
                <header/>
                <body>
                        <trans-unit id="page.title" approved="no">
-                               <source>Page title source</source>
-                       </trans-unit>
-                       <trans-unit id="page.title.theAlps" approved="yes">
-                               <source>Die Alpen!!!</source>
-                       </trans-unit>
+                               <source>S</source> </trans-unit>
+                       <trans-unit id="page.title.theAlps" approved="no">
+                               <source>D</source> </trans-unit>
                        <trans-unit id="mod.web_layout.backendLayouts.centeredNarrow.title" approved="yes">
                                <source>Zentriert schmal</source>
                        </trans-unit>
```


Diff of an updated bilingual target file: 
```diff
--- a/app/web/typo3conf/ext/usersaccassite/Resources/Private/Language/fr.locallang.xlf
+++ b/app/web/typo3conf/ext/usersaccassite/Resources/Private/Language/fr.locallang.xlf
@@ -4,22 +4,20 @@
                <header/>
                <body>
                        <trans-unit id="page.title" approved="no">
-                               <source>Suisse Alpine Club</source>
-                               <target state="translated">Schweizer Alpen-Club SAC Test</target>
-                       </trans-unit>
+                               <source>P</source>
+                               <target state="translated">F</target> </trans-unit>
                        <trans-unit id="page.title.theAlps" approved="no">
                                <source>D</source>
-                               <target state="translated">Les alpes</target> </trans-unit>
+                               <target state="translated">F</target> </trans-unit>
                        <trans-unit id="mod.web_layout.backendLayouts.centeredNarrow.title" approved="no">
                                <source>Z</source>
                                <target state="translated">FR: Zentriert schmal</target> </trans-unit>
                        <trans-unit id="mod.web_layout.backendLayouts.centeredWide.title" approved="no">
                                <source>Z</source>
                                <target state="translated">FR: Zentriert breit</target> </trans-unit>
-                       <trans-unit id="mod.web_layout.backendLayouts.mySac.title" approved="yes">
-                               <source>Mein SAC mit Unterseitenmenü</source>
-                               <target state="translated">Mon CAS avec sous-menus</target>
-                       </trans-unit>
+                       <trans-unit id="mod.web_layout.backendLayouts.mySac.title" approved="no">
+                               <source>M</source>
+                               <target state="translated">F</target> </trans-unit>
                        <trans-unit id="mod.web_layout.backendLayouts.page.title" approved="no">
                                <source>S</source>
                                <target state="translated">Page</target>
```

In never entered a single character string. Neither for source nor for target. All strings seem to get truncated to their first character on save. In weblate, they still appear as multi-character strings. 

Screenshot 2019-05-16 at 18 06 36

**Comment by nijel** [comment]
Thanks, I've now fixed one of the patches and added tests, so hopefully it will be now really working as expected :-).

**Comment by SomeBdyElse** [comment]
Hi @nijel ! Please say when you would like me to test again.

**Comment by nijel** [comment]
It should be ready to test, one patch is unchanged (but rebased, so has different hash).

**Comment by SomeBdyElse** [comment]
Dear @nijel ! I could not find any more issues. Thank you so much for your work.

**Comment by nijel** [comment]
Thanks for testing!

**Pull request merged**
