### PR TITLE
Add basic support for XLIFF states

### PR DESCRIPTION
**Pull request by nijel**
We do not use translate-toolkit here, but rather parse it on our own as
translate-toolkit has a bit strange logic of handling this.

The following states are considered as fuzzy: new, needs-translation,
needs-adaptation, needs-l10n

Issue #2380
Issue #2372

Signed-off-by: Michal Čihař <michal@cihar.com>

Before submitting pull request, please ensure that:

- [x] Every commit has message which describes it
- [x] Every commit is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any code changes come with testcase
- [x] Any new functionality is covered by user documentation

### CODE REVIEW

**Comment by nijel** [comment]
@PowerKiKi As you have played a bit with XLIFF states, I'd like to hear your input on this.

**Comment by PowerKiKi** [comment]
Thanks for reaching out to me, and sorry about my late reply.

I think the documentation should be made more clear by listing exactly which `state` values are read or not, and which `state` values are written. And also how it combines (or not) with `approved` attribute.

I was wondering if a huge table (or several tables?) to describe those read/write mapping would be a nice thing to have for **all** formats. Hopefully it would make it easier to understand what happen between formats for end-users. Maybe something similar to https://github.com/WeblateOrg/weblate/pull/2372#issuecomment-436157111

Also, this is out of scope, but I feel the mixed terms in Weblate code and Weblate GUI are confusing. I think the worst is `STATE_TRANSLATED` that is declared as `_('Translated'))`, but it typically shows up as `"Waiting for review"` in the GUI. Also the obvious "fuzzy" vs `"Need editing"`. If we could standardize the terms used in Weblate code and Weblate GUI (and Weblate docs), it would probably make it easier to understand how to use the product, and to contribute to it.

Otherwise the code itself of this PR looks good to me, but I'd try to improve doc before merging  :)

**Comment by nijel** [comment]
Well most of formats have no states at all so there is nothing to document for them :-). But it could be covered in the features table to make it clear.

The different naming comes from workflow settings (STATE_TRANSLATED is called Translated if review workflow is not used) and history (originally there was Fuzzy state in the UI as well, but the name was confusing, but it really didn't help, see https://github.com/WeblateOrg/weblate/issues/2240).

**Comment by nijel** [comment]
I've extended the features table, that should make it easier to understand what is supported where. Also the states are listed in the xliff docs now.

**Comment by PowerKiKi** [comment]
LGTM !

**Pull request merged**
