### PR TITLE
fix hexlify()

### PR DESCRIPTION
**Pull request by minusf**
`hexlify()` returns `b''` in py3, resulting in usernames like `deleted-2-b'614b67018f'`

This is probably not the most elegant fix, but i dont use python2 anymore, so...

Before submitting pull request, please ensure that:

- [x] Every commit has message which describes it
- [x] Every commit is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any code changes come with testcase
- [x] Any new functionality is covered by user documentation

### CODE REVIEW

**Comment by minusf** [comment]
sorry, i was confused by setup.py and all the six imports :}

**Comment by nijel** [comment]
There should be no six imports left in master branch. The 3.11 was last release supporting Python 2.

**Comment by minusf** [comment]
right, then only `setup.py`:

```
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 2.7",
```

**Comment by nijel** [comment]
I forgot to remove that, done in f068e05d83. Anyway the most important thing was there:

https://github.com/WeblateOrg/weblate/blob/f068e05d839b6dfa98dbb9690178906bfbe31d94/setup.py#L50

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by minusf** [comment]
now i know why i was so confused: 3.11.2 still has `six` imports and we use pypi releases in our project. when i debug stuff it's in these releases, but when i submit patches it's against master..

**Pull request merged**
