### PR TITLE
Pull Request support for Bitbucket Cloud API

### LINKED ISSUE #2344: Pull requests for BitBucket Cloud
**Is your feature request related to a problem? Please describe.**
Weblate currently supports pull requests only for GitHub, it might be useful to have it for BitBucket as well.

**Describe the solution you'd like**
Similarly like with GitHub, Weblate would open pull request on BitBucket instead of directly pushing the code.

**Additional context**
See also https://github.com/WeblateOrg/weblate/issues/1276

### PR DESCRIPTION
**Pull request by gersona**
## Proposed changes
Support for Pull Requests with Bitbucket Cloud is added (Different from #8706).
Authentication uses [App passwords](https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/) instead of [OAuth](https://support.atlassian.com/bitbucket-cloud/docs/use-oauth-on-bitbucket-cloud/#Refresh-tokens) is also available.

Support for OAuth authentication can be discussed on a separate issue

## Checklist

- [x] Lint and unit tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added documentation to describe my feature.
- [x] I have squashed my commits into logic units.
- [x] I have described the changes in the commit messages.

## Other information
fixes #2344

### CODE REVIEW

**Review by nijel — COMMENTED** [review]
I didn't investigate it, but I have to ask: Is there some similarity with Bitbucket Server so that some code reuse would make sense, or is it wholly different?

**Comment by gersona** [comment]
There are some similarities that can indeed be combined. 
The differences are mainly around authentication, API params and responses

**Comment by gersona** [comment]
After a second thought, I don't think there's enough similarities between the 2 to get something in common beyond placeholders in a parent class. There's also the risk of making the code less readable

**Comment by nijel** [comment]
That's fine, I just wanted you to look into that.

**Comment by nijel** [comment]
Thanks, I've added missing changelog entry in 4a0adeb09d90dc6725ea2e1525963fdac103c23e.

**Pull request merged**
