### PR TITLE
automatic translation via machine translation

### PR DESCRIPTION
**Pull request by mlaggner**
Added this feature into the automatic translation view. Calling the function from the view works as expected.

I touched/modified all files I am aware of, but there has been a few places where I did not know what to do:

- urls.py (ehance the regexp `r'^projects/' + TRANSLATION + 'auto/$',` by the -mt one): I did not find out if that extension is needed
- test_autotranslate.py: I did add some basic unit tests, but to do some more detailed testing I could not find out how the test model looks like
- command line execution: I did not understand how this exactly works and how I should implement this feature to the command line functions

beside that I changed everything I was aware of

### CODE REVIEW

**Comment by nijel** [comment]
Thanks, it looks good. What I wonder if it could not share more code with current autotranslate as it seems to be quite similar in the end and you seem to have copied quite amount of existing code (in both implementation, views and tests)...

**Comment by mlaggner** [comment]
just checked that again, but since we have some different entry points (one with a "source" translation project and one with a list of MT engines & threshold), I do not see that there should be shared code..
And according to the "separation of concerns" paradigm I think we should not mix the implementations

**Comment by nijel** [comment]
Okay, I have just quickly looked and didn't really deeply compare the code, but it looked similar. I'll take deeper look after 2.19 is out what should be probably on Wednesday.

**Comment by mlaggner** [comment]
just had an issue with this feature:
If the automatic translation returns a match which is longer than the `max-length` it should be inserted as a suggestion rather than as a _too long_ translation to avoid the maximum length error (https://docs.weblate.org/en/weblate-2.19.1/user/checks.html#check-max-length)

**Comment by nijel** [comment]
Thanks, I've merged your code, but I've decided to share the basics of the auto translation code, see https://github.com/WeblateOrg/weblate/commit/a6bc9cb80e808bf43e78243678716c8e9c5c8aae

**Comment by mlaggner** [comment]
thanks! 
will test it as soon as possible

**Comment by mlaggner** [comment]
just tried it in my test environment and I must say it works perfectly!
Thanks!

**Comment by mlaggner** [comment]
just found an issue with the combination of Weblate and WeblateSimilar:
see the line https://github.com/WeblateOrg/weblate/blob/a6bc9cb80e808bf43e78243678716c8e9c5c8aae/weblate/trans/autotranslate.py#L126 

my assumption of the initial pull request was, that the `weblate` machine translation only offers 100% results; but the weblate engine now combines the two engine from before and thus offers _good_ and _bad_ results.
I think we should only call other engines, if the weblate engine did not respond with a 100% result; if the result from weblate is lower than 100% (even above 80% e.g.), other engines could still offer _better_ results..

what do you think?

**Comment by nijel** [comment]
That sounds reasonable.

**Pull request merged**
