### PR TITLE
fix: add json customize addon's compat

### PR DESCRIPTION
**Pull request by Yoshino-s**
## Proposed changes

Fix json customize addon not work when using i18nextv4 format

## Checklist

- [x ] Lint and unit tests pass locally with my changes.
- [x ] I have added tests that prove my fix is effective or that my feature works.
- [x ] I have added documentation to describe my feature.
- [x ] I have squashed my commits into logic units.
- [ x] I have described the changes in the commit messages.

### CODE REVIEW

**Comment by Yoshino-s** [comment]
hey, the ci seems to crash unexpectedly, is there anyone who can help me?

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Comment by Yoshino-s** [comment]
hey, i', wondering how long will it take for this fix to be added to the hosted weblate?

**Comment by nijel** [comment]
It will be there soon, waiting for some other fixes to deploy...

**Pull request merged**
