### PR TITLE
API: project endpoint to get and create labels

### PR DESCRIPTION
**Pull request by vinceh121**
## Proposed changes

This change adds the `GET,POST /api/projects/:projectSlug/labels/` endpoint, which allows listing labels, and users with the `project.edit` permission to create labels.

## Checklist

- [x] Lint and unit tests pass locally with my changes.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added documentation to describe my feature.
- [x] I have squashed my commits into logic units.
- [x] I have described the changes in the commit messages.

## Other information

This change induces an inconsistency with Unit serialization, as they currently serialize labels as strings. Should they now be serialized as objects?

### CODE REVIEW

**Comment by nijel** [comment]
I think unit labels serializer should be changed, even if it is a breaking change.

Can you please also add tests for this new API?

**Comment by vinceh121** [comment]
I've added tests, modified the tests on units, and now the `GET /api/units/:unitId/` endpoint serializes the labels as objects with id, name and color.

**Comment by nijel** [comment]
Looks good, can you please update the documentation as well_

**Comment by vinceh121** [comment]
I've added the two endpoints to the documentation.

**Pull request merged**
