### PR TITLE
Proposal for fixing #3322

### PR DESCRIPTION
**Pull request by surli**
Before submitting pull request, please ensure that:

- [x] Every commit has message which describes it
- [x] Every commit is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [x] Any code changes come with testcase
- [x] Any new functionality is covered by user documentation

### CODE REVIEW

**Comment by surli** [comment]
@nijel Codefactor is complaining about the new tests since I duplicate some codes, but I didn't want to change the existing test resource. Let me know if I need to improve this.

**Comment by surli** [comment]
Hi @nijel (and happy new year :) ) any feedback on that PR?

**Comment by nijel** [comment]
I still think that this is not good place to address this. The root cause is IMHO API violation in translate-toolkit that it parses those as separate units. It is related to https://github.com/translate/translate/issues/3928. I think the parser should only emit actual strings and include all comments up to the string with it. This is how other formats behave.

**Comment by surli** [comment]
> The root cause is IMHO API violation in translate-toolkit that it parses those as separate units. It is related to translate/translate#3928.

OK, on my side it's a blocker since I need this to implement properly my new formats with all the features we currently have. 
I'm ok to help on fixing this on translate-toolkit side but might need some guidance on what's the expected result then :) 
And for info does translate-toolkit has a specific release process?

**Comment by nijel** [comment]
The fix for translate-toolkit should be here: https://github.com/translate/translate/pull/3931

There is no specific release process on translate-toolkit, usually releases happen when somebody (often it's me) asks the maintainer.

**Pull request closed without merging**
