### PR TITLE
fix sap translation hub to run on python 3

### PR DESCRIPTION
**Pull request by mlaggner**
the translation hub translation engine was not able to be run on python 3

### CODE REVIEW

**Comment by nijel** [comment]
Wouldn't the decoded string work for Python 2 as well? Also it would be great to have this covered by the tests, so that the fix can be verified automatically.

**Comment by mlaggner** [comment]
according to the docs of `base64.b64encode` this method accepts/returns str/str in python 2.7, but byte/byte in python 3
does a decode of a string with a following concatenation to a string work in python 2?

**Comment by nijel** [comment]
It will return unicode string, I'm not sure whether it will work fine in `add_header`. Anyway the tests would give an instant answer for that :-).

**Comment by nijel** [comment]
Merged, thanks for your contribution!

**Pull request merged**
