### PR TITLE
Support alternative fastlane filenames

### PR DESCRIPTION
**Pull request by jspricke**
Used in fdroiddata.

## Checklist

- [ ] Lint and unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added documentation to describe my feature.
- [ ] I have squashed my commits into logic units.
- [ ] I have described the changes in the commit messages.

### CODE REVIEW

**Review by nijel — APPROVED** [review]
Thanks, scheduled for merge.

**Comment by eighthave** [comment]
@jspricke did you try this on fdroiddata yet?  I thought there needed to be other changes, since the fastlane has one summary.txt/short_description.txt per weblate component while fdroiddata would have multiple, one for each app.

**Comment by jspricke** [comment]
@eighthave I guess the file mask needs to be adopted for that. Maybe @nijel has a hint where to do that in the code.

**Comment by nijel** [comment]
Sorry, but I have no clue about fdroiddata.

**Pull request merged**
