### PR TITLE
Autofills uploaded screenshots with filename

### LINKED ISSUE #3818: Autofill uploaded screenshot name with filename
It is tedious having to name all screenshots when the files are already named.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/91359821-autofill-uploaded-screenshot-name-with-filename?utm_campaign=plugin&utm_content=tracker%2F253393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F253393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by flosincapite**
Fixes #3818

This is a WIP, but I'm having trouble testing my changes.

Questions:

1) Is there a way to run only the frontend locally (and use the production backends)? Maybe some undocumented option in rundev.sh?

1a) Alternatively, is there a way I can pre-populate the local DBs with a few projects and languages?

2) I'd like to bypass user creation. Is there a way I can create a user via CLI when I deploy locally?

3) I can't get email to work at all. I've tried setting the relevant EMAIL_* and WEBLATE_EMAIL_* env variables without success. Ideally, I'd like to direct this stuff to a local smtpd server so the emails just print to stdout. I don't want to use "real" email credentials. Any tips?

### CODE REVIEW

**Comment by nijel** [comment]
You can create user by https://docs.weblate.org/en/latest/admin/management.html#createadmin, I've just added import_demo command in 808ff6a880 to create some translations.

**Comment by flosincapite** [comment]
Ah, thanks! I'm able to function as an admin now.

import_demo is giving me some trouble [1]. Any thoughts on how to fix this? My PostgreSQL database seems to be set up properly.

I can just add dummy translations if necessary, but import_demo looks way more convenient.

[1] https://pastebin.com/awr6a7BQ

**Comment by flosincapite** [comment]
Sorry, another question. The dropdown option to add a screenshot is not present in my dev version [see screenshot]. Any ideas?

Screenshot from 2020-05-11 14-31-14

**Comment by nijel** [comment]
* The `import_demo` was added recently, please update your git repo
* The screenshots are managed at the component level, you will find it there

**Comment by julen** [comment]
@nijel if you check the pastebin, @flosincapite already has the `import_demo` command, so the error seems legit.

**Comment by nijel** [comment]
Ah sorry, I missed that. I got confused by error messages on top, that should really be improved (https://github.com/WeblateOrg/weblate/issues/3869).

Anyway back to the traceback - it complains that it doesn't have password set. Maybe you're using wrong settings? Anything in the DJANGO_SETTINGS environment variable?

**Comment by flosincapite** [comment]
No, nothing in DJANGO_SETTINGS, so I assume it's using "default" from [this line](https://github.com/WeblateOrg/weblate/blob/master/manage.py#L28).

I've populated the appropriate fields in weblate/settings.py:DATABASES["default"] with USER: "weblate" and my password. I've made sure the "weblate" user exists and is an admin.

**Comment by flosincapite** [comment]
Apologies for the long delay on this. I'm still having a lot of problems with basic authentication. When I try to run

`python manage.py import_demo`

or 

`python manage.py runserver`

I get an error that ends with this:

```
django.db.utils.OperationalError: FATAL:  password authentication failed for user "weblate"
FATAL:  password authentication failed for user "weblate"
```

I have recently updated my password in postgres:

```$ sudo -u postgres psql
psql (10.12 (Ubuntu 10.12-0ubuntu0.18.04.1))
Type "help" for help.

postgres=# \password weblate
Enter new password: 
Enter it again: 
postgres=# ^C
```

And I have placed that password in `weblate/settings.py`:

```
[...]
DATABASES = {
    "default": {
        # Use 'postgresql' or 'mysql'.
        "ENGINE": "django.db.backends.postgresql",
        # Database name.
        "NAME": "weblate",
        # Database user.
        "USER": "weblate",
        # Database password.
        "PASSWORD": "noshorts",
        # Set to empty string for localhost.
        "HOST": "127.0.0.1",
        # Set to empty string for default.
        "PORT": "",
[...]
```

I'd really like to contribute but I'm stuck. Can anyone help me debug this?

**Comment by nijel** [comment]
Is the settings.py you're editing being used? Try adding some print statement there to check that. Do you have `DJANGO_SETTINGS` environment variable set?

**Comment by flosincapite** [comment]
> Is the settings.py you're editing being used? Try adding some print statement there to check that. Do you have `DJANGO_SETTINGS` environment variable set?

It is being used (verified with a print statement). I don't have DJANGO_SETTINGS; what should they be set to?

**Comment by nijel** [comment]
Sorry, it's actually [DJANGO_SETTINGS_MODULE](https://docs.djangoproject.com/en/3.0/topics/settings/#envvar-DJANGO_SETTINGS_MODULE).

**Comment by flosincapite** [comment]
I have set that variable:

```
DJANGO_SETTINGS_MODULE=weblate.settings
```

I then run

```
python manage.py createadmin
./rundev.sh
```

I can't log in with username `admin`.  It's really strange, because I was able to log in fine before.

**Comment by nijel** [comment]
I don't think that DJANGO_SETTINGS_MODULE works with Docker based `rundev.sh`, but I've never used that one.

The `createadmin` generates random password and prints it, are you using that one?

**Comment by flosincapite** [comment]
Yes, that is the password I am using. I'll try running with manage.py.

**Pull request closed without merging**
