### PR TITLE
zh_Hans to zh_CN

### PR DESCRIPTION
**Pull request by dingpengyu**
hi team

Currently, the Chinese translation of weblate mainly uses (zh_Hans) the old (IE8N) Code,
Replace (zh_HANS) the old IE8N with (zh_CN) the new (IE8N) code.
Fix translation sorting problem (djangojs.po) in (poedit) edits, and ( Language header) error problem.
thanks

### CODE REVIEW

**Comment by nijel** [comment]
What makes you think that zh_Hans is obsolete? It's the correct code for Simplified Chinese, using zh_CN for that is wrong. See for example https://code.djangoproject.com/ticket/18419

**Comment by dingpengyu** [comment]
> What makes you think that zh_Hans is obsolete? It's the correct code for Simplified Chinese, using zh_CN for that is wrong. See for example https://code.djangoproject.com/ticket/18419
Thanks for the clarification, the main reason for submitting this pr is to fix the:
Fix translation sorting problem (djangojs.po) in (poedit) edits, and ( Language header) error .
The poedit editor does not support zh_HANS.
thanks

**Comment by nijel** [comment]
Maybe poedit authors should revisit https://github.com/vslavik/poedit/issues/100...

**Comment by nijel** [comment]
Sorry, we're not going to use obsolete code just because it doesn't work in Poedit.

**Pull request closed without merging**
