### PR TITLE
Fix2076

### PR DESCRIPTION
**Pull request by the-bionic**
Before submitting pull request, please ensure that:

- [ ] Every commit has message which describes it
- [ ] Every commit is needed on it's own, if you have just minor fixes to previous commits, you can squash them
- [ ] Any code changes come with testcase
- [ ] Any new functionality is covered by user documentation

### CODE REVIEW

**Comment by the-bionic** [comment]
Please, any suggestions as to why the selenium test failed?

**Comment by nijel** [comment]
It seems you have done something wrong as you PR contains changes to other files as well

**Comment by nijel** [comment]
I've restarted the selenium tests, it was some temporary error

**Comment by the-bionic** [comment]
The first check that ran failed, saying I have incorrectly signed off. Then it suggested that I run some commands to modify my commit messages, after that it rebased and that is when it all went wrong. Any ideas?

**Comment by nijel** [comment]
Update upstream branch and rebase on top of that, if you don't have it you can add it:

```sh
# Add upstream origin
git remote add upstream https://github.com/WeblateOrg/weblate.git
git remote update upstream

# Rebase your branch on top of current upstream master
git rebase -i upstream/master
# Remove not wanted commits in the editor, keep your commits
# Optionally you can squash your commits into one

# Push changed branch
git push --force origin fix2076
```

**Comment by the-bionic** [comment]
Done. Thanks.

**Comment by nijel** [comment]
Merged, thanks for your contribution!

I've also added basic docs in e5b19e25ea.

**Pull request merged**
