### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Weblate/Application](https://hosted.weblate.org/projects/weblate/application/).

It also includes following components:

* [Weblate/Documentation](https://hosted.weblate.org/projects/weblate/documentation/)

* [Weblate/Application: Javascript](https://hosted.weblate.org/projects/weblate/javascript/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by yangyangdaji** [comment]
@nijel Why does Eric restore changes , My first contribution to the project

**Comment by yangyangdaji** [comment]
> @nijel为什么 Eric 恢复我的更改，请参阅[86c0f74 #diff-8c249de72b4dccbb1306e91c885e2731a3e2065b0b4c239e7f28f33ad6000c49R80](https://github.com/WeblateOrg/weblate/commit/86c0f74c009cec278095992b105b61d8d3319a48#diff-8c249de72b4dccbb1306e91c885e2731a3e2065b0b4c239e7f28f33ad6000c49R80)和[d6f4a6f](https://github.com/WeblateOrg/weblate/commit/d6f4a6f236bff5f6f311e820154734d8d687f546)我对项目的第一个贡献😔

I have resubmitted

**Comment by yangyangdaji** [comment]
> @nijel Why does Eric restore my ,changes , see [86c0f74#diff-8c249de72b4dccbb1306e91c885e2731a3e2065b0b4c239e7f28f33ad6000c49R80](https://github.com/WeblateOrg/weblate/commit/86c0f74c009cec278095992b105b61d8d3319a48#diff-8c249de72b4dccbb1306e91c885e2731a3e2065b0b4c239e7f28f33ad6000c49R80) and [d6f4a6f](https://github.com/WeblateOrg/weblate/commit/d6f4a6f236bff5f6f311e820154734d8d687f546) My first contribution to the project 😔

I have resubmitted

**Comment by Geeyun-JY3** [comment]
@yangyangdaji Please reach follow the glossary when translating. If you want to change a glossary term, please reach a consensus with other translators before changing it. For example, the “e-mail” term is here: https://hosted.weblate.org/translate/weblate/glossary/zh_Hans/?checksum=f057e203dbff2a08

**Comment by yangyangdaji** [comment]
> @yangyangdaji Please follow the glossary while translating. If you want to change a glossary term, please reach a consensus with other translators before changing it. For example, the “e-mail” term is here: https://hosted.weblate.org/translate/weblate/glossary/zh_Hans/?checksum=f057e203dbff2a08

👌 I'll skip it later.

**Comment by yangyangdaji** [comment]
@Geeyun-JY3 Restored pending sync

**Comment by Geeyun-JY3** [comment]
@yangyangdaji You don't need my approval. It is just the rule you should follow in a crowdsourcing project.

**Pull request merged**
